engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
    exclude_fingerprints:
    - afa9b137c4f7bd575eba5b5e6fd11cdf
    - 90499addfcdcfaf453e14c05777d1a8e
    - 8cf604e26389e8acdfe2574db0f65682
    - c4babfbebd23bd530d9b5cfdf6f210f4
    - e7ce486b456863b31df7ed65ebb447b3
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
exclude_paths:
- config/
- tests/
- vendor/
- storage/
