language: php

os:
  - linux
  # PHP is no supported on OS X: https://github.com/travis-ci/travis-ci/issues/2313
  #- osx

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

services:
  - mysql

matrix:
  include:
    - php: 7.0.0
      sudo: required
      dist: precise
      addons:
        apt:
          sources:
            - mysql-5.7-trusty
          packages:
            - mysql-server
            - mysql-client

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN

before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

install:
  - chmod -R 777 bootstrap/cache
  - chmod -R 777 storage
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv

script:
  - vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - php artisan migrate:rollback --env=testing --no-interaction -vvv
  - php vendor/bin/codacycoverage clover
  - vendor/bin/test-reporter
