language: php

env:
  global:
  - secure: $COVERITY_SCAN_TOKEN

addons:
    code_climate:
        repo_token: $CODE_CLIMATE_TOKEN
    coverity_scan:
      project:
        name: "Saibamen/HotelManager"
        description: "Build submitted via Travis CI"
      notification_email: saibamenppl@gmail.com
      build_command_prepend: "cp .env.travis .env"
      build_command:   "vendor/bin/phpunit"
      branch_pattern: master

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script:
  - chmod -R 777 bootstrap/cache
  - chmod -R 777 storage
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction -vvv

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php artisan migrate:rollback --env=testing --no-interaction -vvv

after_success:
  - vendor/bin/test-reporter
