# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.8-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=homestead_test

    working_directory: ~/laravel

    steps:
      - checkout

      # MySQL
      - run: sudo apt-get update
      - run: sudo apt-get install -y mysql-server
      - run: sudo apt install -y libsqlite3-dev
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo service mysql start

      - run: composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-

      - run:
          name: Display versions
          command: |
            php -v
            composer --version

      - run: sudo chmod -R 775 storage
      - run: sudo chmod -R 775 bootstrap/cache
      - run: cp .env.travis .env
      - run: mysql -u root -e 'create database homestead_test;'
      - run: composer update --no-interaction
      - run: php artisan key:generate

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=testing --force
      - run: php artisan db:seed --env=testing --database=testing --no-interaction -vvv

      # run tests!
      - run: vendor/bin/phpunit

      - run: php artisan migrate:rollback --env=testing --database=testing --no-interaction -vvv
